<?php
return [
    '01' => ['id' => 'adana', 'name' => 'Adana', 'region' => 'Akdeniz'],
    '02' => ['id' => 'adiyaman', 'name' => 'Adıyaman', 'region' => 'Güneydoğu Anadolu'],
    '03' => ['id' => 'afyonkarahisar', 'name' => 'Afyonkarahisar', 'region' => 'Ege'],
    '04' => ['id' => 'agri', 'name' => 'Ağrı', 'region' => 'Doğu Anadolu'],
    '05' => ['id' => 'amasya', 'name' => 'Amasya', 'region' => 'Karadeniz'],
    '06' => ['id' => 'ankara', 'name' => 'Ankara', 'region' => 'İç Anadolu'],
    '07' => ['id' => 'antalya', 'name' => 'Antalya', 'region' => 'Akdeniz'],
    '08' => ['id' => 'artvin', 'name' => 'Artvin', 'region' => 'Karadeniz'],
    '09' => ['id' => 'aydin', 'name' => 'Aydın', 'region' => 'Ege'],
    '10' => ['id' => 'balikesir', 'name' => 'Balıkesir', 'region' => 'Marmara'],
    '11' => ['id' => 'bilecik', 'name' => 'Bilecik', 'region' => 'Marmara'],
    '12' => ['id' => 'bingol', 'name' => 'Bingöl', 'region' => 'Doğu Anadolu'],
    '13' => ['id' => 'bitlis', 'name' => 'Bitlis', 'region' => 'Doğu Anadolu'],
    '14' => ['id' => 'bolu', 'name' => 'Bolu', 'region' => 'Karadeniz'],
    '15' => ['id' => 'burdur', 'name' => 'Burdur', 'region' => 'Akdeniz'],
    '16' => ['id' => 'bursa', 'name' => 'Bursa', 'region' => 'Marmara'],
    '17' => ['id' => 'canakkale', 'name' => 'Çanakkale', 'region' => 'Marmara'],
    '18' => ['id' => 'cankiri', 'name' => 'Çankırı', 'region' => 'İç Anadolu'],
    '19' => ['id' => 'corum', 'name' => 'Çorum', 'region' => 'Karadeniz'],
    '20' => ['id' => 'denizli', 'name' => 'Denizli', 'region' => 'Ege'],
    '21' => ['id' => 'diyarbakir', 'name' => 'Diyarbakır', 'region' => 'Güneydoğu Anadolu'],
    '22' => ['id' => 'edirne', 'name' => 'Edirne', 'region' => 'Marmara'],
    '23' => ['id' => 'elazig', 'name' => 'Elazığ', 'region' => 'Doğu Anadolu'],
    '24' => ['id' => 'erzincan', 'name' => 'Erzincan', 'region' => 'Doğu Anadolu'],
    '25' => ['id' => 'erzurum', 'name' => 'Erzurum', 'region' => 'Doğu Anadolu'],
    '26' => ['id' => 'eskisehir', 'name' => 'Eskişehir', 'region' => 'İç Anadolu'],
    '27' => ['id' => 'gaziantep', 'name' => 'Gaziantep', 'region' => 'Güneydoğu Anadolu'],
    '28' => ['id' => 'giresun', 'name' => 'Giresun', 'region' => 'Karadeniz'],
    '29' => ['id' => 'gumushane', 'name' => 'Gümüşhane', 'region' => 'Karadeniz'],
    '30' => ['id' => 'hakkari', 'name' => 'Hakkari', 'region' => 'Doğu Anadolu'],
    '31' => ['id' => 'hatay', 'name' => 'Hatay', 'region' => 'Akdeniz'],
    '32' => ['id' => 'isparta', 'name' => 'Isparta', 'region' => 'Akdeniz'],
    '33' => ['id' => 'mersin', 'name' => 'Mersin', 'region' => 'Akdeniz'],
    '34' => ['id' => 'istanbul', 'name' => 'İstanbul', 'region' => 'Marmara'],
    '35' => ['id' => 'izmir', 'name' => 'İzmir', 'region' => 'Ege'],
    '36' => ['id' => 'kars', 'name' => 'Kars', 'region' => 'Doğu Anadolu'],
    '37' => ['id' => 'kastamonu', 'name' => 'Kastamonu', 'region' => 'Karadeniz'],
    '38' => ['id' => 'kayseri', 'name' => 'Kayseri', 'region' => 'İç Anadolu'],
    '39' => ['id' => 'kirklareli', 'name' => 'Kırklareli', 'region' => 'Marmara'],
    '40' => ['id' => 'kirsehir', 'name' => 'Kırşehir', 'region' => 'İç Anadolu'],
    '41' => ['id' => 'kocaeli', 'name' => 'Kocaeli', 'region' => 'Marmara'],
    '42' => ['id' => 'konya', 'name' => 'Konya', 'region' => 'İç Anadolu'],
    '43' => ['id' => 'kutahya', 'name' => 'Kütahya', 'region' => 'Ege'],
    '44' => ['id' => 'malatya', 'name' => 'Malatya', 'region' => 'Doğu Anadolu'],
    '45' => ['id' => 'manisa', 'name' => 'Manisa', 'region' => 'Ege'],
    '46' => ['id' => 'kahramanmaras', 'name' => 'Kahramanmaraş', 'region' => 'Akdeniz'],
    '47' => ['id' => 'mardin', 'name' => 'Mardin', 'region' => 'Güneydoğu Anadolu'],
    '48' => ['id' => 'mugla', 'name' => 'Muğla', 'region' => 'Ege'],
    '49' => ['id' => 'mus', 'name' => 'Muş', 'region' => 'Doğu Anadolu'],
    '50' => ['id' => 'nevsehir', 'name' => 'Nevşehir', 'region' => 'İç Anadolu'],
    '51' => ['id' => 'nigde', 'name' => 'Niğde', 'region' => 'İç Anadolu'],
    '52' => ['id' => 'ordu', 'name' => 'Ordu', 'region' => 'Karadeniz'],
    '53' => ['id' => 'rize', 'name' => 'Rize', 'region' => 'Karadeniz'],
    '54' => ['id' => 'sakarya', 'name' => 'Sakarya', 'region' => 'Marmara'],
    '55' => ['id' => 'samsun', 'name' => 'Samsun', 'region' => 'Karadeniz'],
    '56' => ['id' => 'siirt', 'name' => 'Siirt', 'region' => 'Güneydoğu Anadolu'],
    '57' => ['id' => 'sinop', 'name' => 'Sinop', 'region' => 'Karadeniz'],
    '58' => ['id' => 'sivas', 'name' => 'Sivas', 'region' => 'İç Anadolu'],
    '59' => ['id' => 'tekirdag', 'name' => 'Tekirdağ', 'region' => 'Marmara'],
    '60' => ['id' => 'tokat', 'name' => 'Tokat', 'region' => 'Karadeniz'],
    '61' => ['id' => 'trabzon', 'name' => 'Trabzon', 'region' => 'Karadeniz'],
    '62' => ['id' => 'tunceli', 'name' => 'Tunceli', 'region' => 'Doğu Anadolu'],
    '63' => ['id' => 'sanliurfa', 'name' => 'Şanlıurfa', 'region' => 'Güneydoğu Anadolu'],
    '64' => ['id' => 'usak', 'name' => 'Uşak', 'region' => 'Ege'],
    '65' => ['id' => 'van', 'name' => 'Van', 'region' => 'Doğu Anadolu'],
    '66' => ['id' => 'yozgat', 'name' => 'Yozgat', 'region' => 'İç Anadolu'],
    '67' => ['id' => 'zonguldak', 'name' => 'Zonguldak', 'region' => 'Karadeniz'],
    '68' => ['id' => 'aksaray', 'name' => 'Aksaray', 'region' => 'İç Anadolu'],
    '69' => ['id' => 'bayburt', 'name' => 'Bayburt', 'region' => 'Karadeniz'],
    '70' => ['id' => 'karaman', 'name' => 'Karaman', 'region' => 'İç Anadolu'],
    '71' => ['id' => 'kirikkale', 'name' => 'Kırıkkale', 'region' => 'İç Anadolu'],
    '72' => ['id' => 'batman', 'name' => 'Batman', 'region' => 'Güneydoğu Anadolu'],
    '73' => ['id' => 'sirnak', 'name' => 'Şırnak', 'region' => 'Güneydoğu Anadolu'],
    '74' => ['id' => 'bartin', 'name' => 'Bartın', 'region' => 'Karadeniz'],
    '75' => ['id' => 'ardahan', 'name' => 'Ardahan', 'region' => 'Doğu Anadolu'],
    '76' => ['id' => 'igdir', 'name' => 'Iğdır', 'region' => 'Doğu Anadolu'],
    '77' => ['id' => 'yalova', 'name' => 'Yalova', 'region' => 'Marmara'],
    '78' => ['id' => 'karabuk', 'name' => 'Karabük', 'region' => 'Karadeniz'],
    '79' => ['id' => 'kilis', 'name' => 'Kilis', 'region' => 'Güneydoğu Anadolu'],
    '80' => ['id' => 'osmaniye', 'name' => 'Osmaniye', 'region' => 'Akdeniz'],
    '81' => ['id' => 'duzce', 'name' => 'Düzce', 'region' => 'Karadeniz'],
    '00' => ['id' => 'kuzey-kibris', 'name' => 'Kuzey Kıbrıs', 'region' => 'Yavru Vatan'],
];
